#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>


#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#define AUDIO_HP_PIN GPIO_NUM_3
#define AUDIO_CODEC_PA_PIN GPIO_NUM_11
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_9
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_10
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define DISPLAY_SWAP_XY true
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false


#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_48
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

// Pin Definitions
#define LCD_NUM_CS GPIO_NUM_40
#define LCD_NUM_DC GPIO_NUM_39
#define LCD_NUM_RD GPIO_NUM_47
#define LCD_NUM_WR GPIO_NUM_38
#define LCD_NUM_RST GPIO_NUM_42
#define LCD_NUM_TE GPIO_NUM_41

#define GPIO_LCD_D0 GPIO_NUM_21
#define GPIO_LCD_D1 GPIO_NUM_18
#define GPIO_LCD_D2 GPIO_NUM_17
#define GPIO_LCD_D3 GPIO_NUM_16
#define GPIO_LCD_D4 GPIO_NUM_15
#define GPIO_LCD_D5 GPIO_NUM_14
#define GPIO_LCD_D6 GPIO_NUM_13
#define GPIO_LCD_D7 GPIO_NUM_12

#define CHARGE_CHECK GPIO_NUM_41
#define BAT_CHECK GPIO_NUM_2
#define POWER_EN GPIO_NUM_NC


#define ZY_OTA_EN 1
#endif // _BOARD_CONFIG_H_
